#!/usr/bin/env bash

alias helmcode='cd $GOPATH/src/k8s.io/kubernetes/helm'
alias walksee='cd $GOPATH/src/github.com/michelleN/walksee'
alias draftcode='cd $GOPATH/src/github.com/Azure/draft'
alias draft-examples='cd $GOPATH/src/github.com/Azure/draft/examples/'

alias k='kubectl'
alias ks='kubectl -n kube-system'

alias fixzoom='sudo killall VDCAssistant'

# shortcuts
alias steering='cat $HOME/.shortcuts/steering.txt'
